vich_uploader:
    db_driver: orm

    mappings:
        upload_videos:
            uri_prefix: /videos
            upload_destination: '%kernel.project_dir%/public/videos'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
